apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-dotnet-deployment
  labels:
    app: dotnetd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetd
  template:
    metadata:
      labels:
        app: dotnetd
    spec:
      containers:
        - name: dotnetd
          image: azacrforsas.azurecr.io/app1/welcometodotnet:v1
          ports:
            - containerPort: 80
     # imagePullSecrets:
     #   - name: azacrforsas
        #  imagePullPolicy: Always                         
         
---  
apiVersion: v1
kind: Service
metadata:
  name: dotnetd-clusterip-service
  labels:
    app: dotnetd
spec:
  type: ClusterIP
  selector:
    app: dotnetd
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-service
  annotation:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
       paths:
         - path: /
           pathType: Prefix
           backend:
            service: dotnetd-ClusterIP-service
              name:
              port:
                name:
                number: 80
