name: deploydotnettok8s
on:
   workflow_dispatch:
  

permissions:
      id-token: write
      contents: read
jobs: 
  AKS-Cluster-Deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: AKS
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: 'Az CLI login'
       
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.ARM_OIDC_TOKEN }}
      - name: Deploy Application
        run: |
          az login
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials -n cluster-smart-snapper -g demorg-careful-pipefish
          az aks update -n cluster-smart-snapper -g demorg-careful-pipefish --attach-acr azacrforsas
      #    kubectl apply -f ./AKSApp/demoappdeploy.yaml
        
      - name: install Ingress Contoller
        run: |   
           kubectl create namespace ingress-sas
           helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
           helm repo add stable https://charts.helm.sh/stable/
           helm repo update
           helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx  --namespace  ingress-sas --create-namespace --set controller.service.loadBalancerIP="4.247.29.19"
      
           kubectl apply -f ./AKSApp/demoappdeploy.yaml
      #     helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-sas --set controller.replicaCount=2 --set controller.nodeSelector."beta\.kubernetes\io/os"=linux --set defaultBackend.nodeSelector."beta\.kubernetes\io/os"=linux --set controller.service.externalTrafficPolicy=Local --set controller.service.loadBalancerIP="4.247.29.19"
                
      #     kubectl apply -f ./AKSApp/demoappdeploy.yaml
           
   #       sleep 40
